platform :ios, '9.0'

inhibit_all_warnings!

target 'ColorfulWoodUIBase' do

pod 'Masonry'
pod 'ColorfulWoodCategories'
pod 'ColorfulWoodPoint'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'JSONModel'
pod 'ColorfulWoodNavigationBar'
pod 'ColorfulWoodTools'                     #弹窗提示等
end
